Set principal unit name and model name in context for template rendering.
juju-solutions/layer-beats-base pull request #20
Opened 2018-02-13 14:00 UTC by tasdomas

This will be used to fix an issue in the filebeat charm, where filebeat run by the charm does not correctly report the principal unit name.

2018-02-14 18:46 UTC, kwmonroe requested changes
Couple minor changes needed imo.

2018-02-14 18:46 UTC, kwmonroe commented on lib/elasticbeats.py
> +    principal_name = getenv('JUJU_PRINCIPAL_UNIT')
Please use the `hookenv.principal_unit` charmhelper:

https://github.com/juju/charm-helpers/blob/master/charmhelpers/core/hookenv.py#L208

2018-02-14 18:46 UTC, kwmonroe commented on lib/elasticbeats.py
> +        principal_name = getenv('JUJU_REMOTE_UNIT')
I know we had `REMOTE_UNIT` before this proposal, but I don't think that is ever the right answer when trying to find our principal.  I think we should drop this and alter the condition to be something like:

```
if principal_name:
    cache.set('principal_name', principal_name)
```

2018-02-15 20:11 UTC, tasdomas commented
@kwmonroe - thanks for the review!
I've updated the PR.

2018-02-20 16:22 UTC, kwmonroe approved these changes
I'll bring this in as-is, but it will change a bit as i merge #24 on top.

2018-02-20 16:23 UTC, merged